
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Entry entry1;

	private global::Gtk.Table table2;

	private global::Gtk.Button button;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Button buttonD;

	private global::Gtk.Button buttonE;

	private global::Gtk.Button buttone1;

	private global::Gtk.Button buttonm;

	private global::Gtk.Button buttonM;

	private global::Gtk.Button buttonX;

	private global::Gtk.Label labelResultado;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.vbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table2 = new global::Gtk.Table(((uint)(4)), ((uint)(4)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.button = new global::Gtk.Button();
		this.button.CanFocus = true;
		this.button.Name = "button";
		this.button.UseUnderline = true;
		this.button.Label = global::Mono.Unix.Catalog.GetString("    0     ");
		this.table2.Add(this.button);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.button]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table2.Add(this.button1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.button1]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table2.Add(this.button2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.button2]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table2.Add(this.button3);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.button3]));
		w5.LeftAttach = ((uint)(2));
		w5.RightAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table2.Add(this.button4);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.button4]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table2.Add(this.button5);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.button5]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table2.Add(this.button6);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2[this.button6]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table2.Add(this.button7);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2[this.button7]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.button8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table2.Add(this.button8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2[this.button8]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table2.Add(this.button9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.button9]));
		w11.TopAttach = ((uint)(2));
		w11.BottomAttach = ((uint)(3));
		w11.LeftAttach = ((uint)(2));
		w11.RightAttach = ((uint)(3));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonD = new global::Gtk.Button();
		this.buttonD.CanFocus = true;
		this.buttonD.Name = "buttonD";
		this.buttonD.UseUnderline = true;
		this.buttonD.Label = global::Mono.Unix.Catalog.GetString("     /     ");
		this.table2.Add(this.buttonD);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonD]));
		w12.TopAttach = ((uint)(3));
		w12.BottomAttach = ((uint)(4));
		w12.LeftAttach = ((uint)(3));
		w12.RightAttach = ((uint)(4));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonE = new global::Gtk.Button();
		this.buttonE.CanFocus = true;
		this.buttonE.Name = "buttonE";
		this.buttonE.UseUnderline = true;
		this.buttonE.Label = global::Mono.Unix.Catalog.GetString("enter");
		this.table2.Add(this.buttonE);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonE]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		w13.LeftAttach = ((uint)(2));
		w13.RightAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttone1 = new global::Gtk.Button();
		this.buttone1.CanFocus = true;
		this.buttone1.Name = "buttone1";
		this.buttone1.UseUnderline = true;
		this.buttone1.Label = global::Mono.Unix.Catalog.GetString("            ");
		this.table2.Add(this.buttone1);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2[this.buttone1]));
		w14.TopAttach = ((uint)(3));
		w14.BottomAttach = ((uint)(4));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonm = new global::Gtk.Button();
		this.buttonm.CanFocus = true;
		this.buttonm.Name = "buttonm";
		this.buttonm.UseUnderline = true;
		this.buttonm.Label = global::Mono.Unix.Catalog.GetString("-");
		this.table2.Add(this.buttonm);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonm]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.LeftAttach = ((uint)(3));
		w15.RightAttach = ((uint)(4));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonM = new global::Gtk.Button();
		this.buttonM.CanFocus = true;
		this.buttonM.Name = "buttonM";
		this.buttonM.UseUnderline = true;
		this.buttonM.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table2.Add(this.buttonM);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonM]));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.buttonX = new global::Gtk.Button();
		this.buttonX.CanFocus = true;
		this.buttonX.Name = "buttonX";
		this.buttonX.UseUnderline = true;
		this.buttonX.Label = global::Mono.Unix.Catalog.GetString("x");
		this.table2.Add(this.buttonX);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2[this.buttonX]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table2]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelResultado = new global::Gtk.Label();
		this.labelResultado.Name = "labelResultado";
		this.labelResultado.LabelProp = global::Mono.Unix.Catalog.GetString("Resultado");
		this.vbox1.Add(this.labelResultado);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelResultado]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 217;
		this.DefaultHeight = 205;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonX.Clicked += new global::System.EventHandler(this.OnButtonxClicked);
		this.buttonM.Clicked += new global::System.EventHandler(this.OnButton14Clicked);
		this.buttonm.Clicked += new global::System.EventHandler(this.OnButton15Clicked);
		this.buttone1.Clicked += new global::System.EventHandler(this.OnButtone1Clicked);
		this.buttonE.Clicked += new global::System.EventHandler(this.OnButtoneClicked);
		this.buttonD.Clicked += new global::System.EventHandler(this.OnButtondClicked);
		this.button9.Clicked += new global::System.EventHandler(this.OnButton9Clicked);
		this.button8.Clicked += new global::System.EventHandler(this.OnButton8Clicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button6.Clicked += new global::System.EventHandler(this.OnButton6Clicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.On4Clicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button.Clicked += new global::System.EventHandler(this.OnButtonClicked);
	}
}
